"""Add feature_flag table.

Revision ID: 67196370bc66
Revises: 29bc7a70d50f
Create Date: 2026-09-13 20:11:42.848965
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67196370bc66"
down_revision: str | Sequence[str] | None = "29bc7a70d50f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flag",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("rollout_percent", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("rollout_percent BETWEEN 0 AND 100", name=op.f("ck_feature_flag_rollout_percent")),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], name=op.f("fk_feature_flag_updated_by_user"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flag")),
    )
    op.create_index(op.f("ix_feature_flag_key"), "feature_flag", ["key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feature_flag_key"), table_name="feature_flag")
    op.drop_table("feature_flag")
    # ### end Alembic commands ###
