"""Add tool request table.

Revision ID: 758745c9ded3
Revises: d2f0c31a77b4
Create Date: 2026-09-13 21:29:10.361256
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "758745c9ded3"
down_revision: str | Sequence[str] | None = "d2f0c31a77b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_request",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("requester_user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug_hint", sa.String(length=50), nullable=False),
        sa.Column("users", sa.Text(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("today", sa.Text(), nullable=False),
        sa.Column("states", sa.Text(), nullable=False),
        sa.Column("must_never_happen", sa.Text(), nullable=False),
        sa.Column("provable", sa.Text(), nullable=False),
        sa.Column("data_sources", sa.Text(), nullable=False),
        sa.Column("volume", sa.Text(), nullable=False),
        sa.Column("success", sa.Text(), nullable=False),
        sa.Column("out_of_scope", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=True),
        sa.Column("session_url", sa.String(length=500), nullable=True),
        sa.Column("dispatch_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["requester_user_id"], ["user.id"], name=op.f("fk_tool_request_requester_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_request")),
    )
    op.create_index(op.f("ix_tool_request_requester_user_id"), "tool_request", ["requester_user_id"], unique=False)
    op.create_index(op.f("ix_tool_request_status"), "tool_request", ["status"], unique=False)
    op.create_index(op.f("ix_tool_request_title"), "tool_request", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_request_title"), table_name="tool_request")
    op.drop_index(op.f("ix_tool_request_status"), table_name="tool_request")
    op.drop_index(op.f("ix_tool_request_requester_user_id"), table_name="tool_request")
    op.drop_table("tool_request")
    # ### end Alembic commands ###
