"""Add refunds tables.

Revision ID: 954bdea01641
Revises: 758745c9ded3
Create Date: 2026-09-14 00:52:59.362362
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "954bdea01641"
down_revision: str | Sequence[str] | None = "758745c9ded3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refunds_request",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("customer_ref", sa.String(length=64), nullable=False),
        sa.Column("order_ref", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("decided_by", sa.Integer(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_by", sa.Integer(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["user.id"], name=op.f("fk_refunds_request_decided_by_user"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["processed_by"], ["user.id"], name=op.f("fk_refunds_request_processed_by_user"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["user.id"], name=op.f("fk_refunds_request_requested_by_user"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refunds_request")),
    )
    op.create_index(op.f("ix_refunds_request_customer_ref"), "refunds_request", ["customer_ref"], unique=False)
    op.create_index(op.f("ix_refunds_request_order_ref"), "refunds_request", ["order_ref"], unique=False)
    op.create_index(op.f("ix_refunds_request_processed_at"), "refunds_request", ["processed_at"], unique=False)
    op.create_index(op.f("ix_refunds_request_requested_by"), "refunds_request", ["requested_by"], unique=False)
    op.create_index(op.f("ix_refunds_request_state"), "refunds_request", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refunds_request_state"), table_name="refunds_request")
    op.drop_index(op.f("ix_refunds_request_requested_by"), table_name="refunds_request")
    op.drop_index(op.f("ix_refunds_request_processed_at"), table_name="refunds_request")
    op.drop_index(op.f("ix_refunds_request_order_ref"), table_name="refunds_request")
    op.drop_index(op.f("ix_refunds_request_customer_ref"), table_name="refunds_request")
    op.drop_table("refunds_request")
    # ### end Alembic commands ###
